### ISSUE TITLE
An NPE bug when fighting with the MoonQueen

### ISSUE THREAD

**Issue by NattoCB** [elseytd/TheAurorian#21] opened 2020-10-07 16:41 UTC
**Describe the bug**
An NPE bug when fighting with the MoonQueen.
at com.elseytd.theaurorian.Entities.Boss.MoonQueen_AICharge.func_75246_d(MoonQueen_AICharge.java:111)

**To Reproduce**
fighting with the MoonQueen will have the chance that causing NPE

**Versions/Environtment**
theaurorian-1.12.2-release-sept1520
modpack's info has contained in the link below

**If you have a Crash Log**
https://paste.ubuntu.com/p/DgX3r8BQYR/

By the way, this is the most comfortable mod I have ever play during this year, 
Thanks a lot 👍

**Comment by shiroroku** [comment] 2020-10-07 18:52
I wasn't able to reproduce it since I need a full mod list, but I was able to find a bug where the crash happened and it should be fixed now https://github.com/elseytd/TheAurorian/commit/b9ca2f2c129a973e64eced2590ad39976c7faa45

**Closed as completed by shiroroku** 2020-10-07 18:52 UTC
Labels: bug
